-- ============================================================================
-- FILE INI SUDAH TIDAK DIPAKAI -- DUPLIKAT BASI, JANGAN DIJALANKAN.
-- ============================================================================
-- Versi file ini ketinggalan kolom multi-currency (mata_uang/kurs/jumlah_idr),
-- kolom refresh harga otomatis aset (simbol/jumlah_unit/sumber_harga), dan
-- tabel rate_limits (dipakai fitur "Tanya AI").
--
-- Gunakan "schema.sql" di folder ROOT repo ini, BUKAN file ini.
--
-- Kalau kamu terlanjur menjalankan versi lama file ini sebelumnya, cukup
-- jalankan "schema.sql" (root) sekarang -- semua perintahnya aman diulang
-- ("if not exists"), tidak akan menghapus/menimpa data yang sudah ada, cuma
-- melengkapi kolom & tabel yang belum ada.
--
-- File ini sengaja dibiarkan ada (bukan dihapus) sebagai penanda, supaya
-- siapa pun yang masih pegang link/bookmark lama ke path ini tidak menjalankan
-- schema basi secara tidak sengaja. Kalau kamu mengelola repo ini sendiri lewat
-- Git, silakan hapus file ini kapan saja -- lihat README.md bagian 12.
-- ============================================================================
